#pragma once

// Dialog IDs
#define IDD_NOWBAR_PREFERENCES     102

// Tab control
#define IDC_TAB_CONTROL            1001

// General tab controls
#define IDC_THEME_MODE_LABEL       1101
#define IDC_THEME_MODE_COMBO       1102
#define IDC_COVER_MARGIN_LABEL     1103
#define IDC_COVER_MARGIN_COMBO     1104
#define IDC_BAR_STYLE_LABEL        1105
#define IDC_BAR_STYLE_COMBO        1106
#define IDC_MOOD_ICON_LABEL        1107
#define IDC_MOOD_ICON_COMBO        1108
#define IDC_MINIPLAYER_ICON_LABEL  1109
#define IDC_MINIPLAYER_ICON_COMBO  1110
#define IDC_CUSTOM_BUTTON_LABEL    1111
#define IDC_CUSTOM_BUTTON_COMBO    1112
#define IDC_CUSTOM_ACTION_LABEL    1113
#define IDC_CUSTOM_ACTION_COMBO    1114
#define IDC_CUSTOM_URL_LABEL       1115
#define IDC_CUSTOM_URL_EDIT        1116
#define IDC_CUSTOM_EXE_LABEL       1117
#define IDC_CUSTOM_EXE_EDIT        1118
#define IDC_CUSTOM_EXE_BROWSE      1119
#define IDC_CUSTOM_FB2K_LABEL      1120
#define IDC_CUSTOM_FB2K_EDIT       1121

// Fonts tab controls
#define IDC_FONTS_GROUP            1201
#define IDC_TRACK_FONT_LABEL       1202
#define IDC_TRACK_FONT_DISPLAY     1203
#define IDC_TRACK_FONT_SELECT      1204
#define IDC_ARTIST_FONT_LABEL      1205
#define IDC_ARTIST_FONT_DISPLAY    1206
#define IDC_ARTIST_FONT_SELECT     1207
