#pragma once

// Dialog IDs
#define IDD_NOWBAR_PREFERENCES     102

// Tab control
#define IDC_TAB_CONTROL            1001

// Display Format section (General tab - at top)
#define IDC_DISPLAY_FORMAT_GROUP   1090
#define IDC_LINE1_FORMAT_LABEL     1091
#define IDC_LINE1_FORMAT_EDIT      1092
#define IDC_LINE2_FORMAT_LABEL     1093
#define IDC_LINE2_FORMAT_EDIT      1094

// General tab controls
#define IDC_THEME_MODE_LABEL       1101
#define IDC_THEME_MODE_COMBO       1102
#define IDC_COVER_MARGIN_LABEL     1103
#define IDC_COVER_MARGIN_COMBO     1104
#define IDC_BAR_STYLE_LABEL        1105
#define IDC_BAR_STYLE_COMBO        1106
#define IDC_MOOD_ICON_LABEL        1107
#define IDC_MOOD_ICON_COMBO        1108
#define IDC_MINIPLAYER_ICON_LABEL  1109
#define IDC_MINIPLAYER_ICON_COMBO  1110
#define IDC_CUSTOM_BUTTON_LABEL    1111
#define IDC_CUSTOM_BUTTON_COMBO    1112
#define IDC_CUSTOM_ACTION_LABEL    1113
#define IDC_CUSTOM_ACTION_COMBO    1114
#define IDC_CUSTOM_URL_LABEL       1115
#define IDC_CUSTOM_URL_EDIT        1116
#define IDC_CUSTOM_EXE_LABEL       1117
#define IDC_CUSTOM_EXE_EDIT        1118
#define IDC_CUSTOM_EXE_BROWSE      1119
#define IDC_CUSTOM_FB2K_LABEL      1120
#define IDC_CUSTOM_FB2K_EDIT       1121
#define IDC_HOVER_CIRCLES_LABEL    1122
#define IDC_HOVER_CIRCLES_COMBO    1123
#define IDC_ALTERNATE_ICONS_LABEL  1124
#define IDC_ALTERNATE_ICONS_COMBO  1125
#define IDC_AUTOHIDE_CBUTTONS_LABEL 1126
#define IDC_AUTOHIDE_CBUTTONS_COMBO 1127
#define IDC_GLASS_EFFECT_LABEL     1128
#define IDC_GLASS_EFFECT_COMBO     1129
#define IDC_BACKGROUND_STYLE_LABEL 1130
#define IDC_BACKGROUND_STYLE_COMBO 1131
#define IDC_STOP_ICON_LABEL        1132
#define IDC_STOP_ICON_COMBO        1133
#define IDC_SMOOTH_ANIMATIONS_LABEL 1134
#define IDC_SMOOTH_ANIMATIONS_COMBO 1135
#define IDC_SUPER_ICON_LABEL       1136
#define IDC_SUPER_ICON_COMBO       1137
#define IDC_COVER_ARTWORK_LABEL    1138
#define IDC_COVER_ARTWORK_COMBO    1139
#define IDC_STOP_AFTER_CURRENT_LABEL 1155
#define IDC_STOP_AFTER_CURRENT_COMBO 1156

// Color picker controls (Appearance tab)
#define IDC_BUTTON_ACCENT_LABEL    1140
#define IDC_BUTTON_ACCENT_BTN      1141
#define IDC_PROGRESS_ACCENT_LABEL  1142
#define IDC_PROGRESS_ACCENT_BTN    1143
#define IDC_VOLUME_ACCENT_LABEL    1144
#define IDC_VOLUME_ACCENT_BTN      1145

// Fonts tab controls
#define IDC_FONTS_GROUP            1201
#define IDC_TRACK_FONT_LABEL       1202
#define IDC_TRACK_FONT_DISPLAY     1203
#define IDC_TRACK_FONT_SELECT      1204
#define IDC_ARTIST_FONT_LABEL      1205
#define IDC_ARTIST_FONT_DISPLAY    1206
#define IDC_ARTIST_FONT_SELECT     1207
#define IDC_TIME_FONT_LABEL        1208
#define IDC_TIME_FONT_DISPLAY      1209
#define IDC_TIME_FONT_SELECT       1210

// Custom Button tab controls
#define IDC_CBUTTON_ENABLE_LABEL   1301
#define IDC_CBUTTON_ACTION_LABEL   1302
#define IDC_CBUTTON1_ENABLE        1303
#define IDC_CBUTTON1_ACTION        1304
#define IDC_CBUTTON2_ENABLE        1305
#define IDC_CBUTTON2_ACTION        1306
#define IDC_CBUTTON3_ENABLE        1307
#define IDC_CBUTTON3_ACTION        1308
#define IDC_CBUTTON4_ENABLE        1309
#define IDC_CBUTTON4_ACTION        1310
#define IDC_CBUTTON_PATH_LABEL     1311
#define IDC_CBUTTON1_PATH          1312
#define IDC_CBUTTON1_BROWSE        1313
#define IDC_CBUTTON2_PATH          1314
#define IDC_CBUTTON2_BROWSE        1315
#define IDC_CBUTTON3_PATH          1316
#define IDC_CBUTTON3_BROWSE        1317
#define IDC_CBUTTON4_PATH          1318
#define IDC_CBUTTON4_BROWSE        1319
#define IDC_CBUTTON5_ENABLE        1320
#define IDC_CBUTTON5_ACTION        1321
#define IDC_CBUTTON5_PATH          1322
#define IDC_CBUTTON5_BROWSE        1323
#define IDC_CBUTTON6_ENABLE        1324
#define IDC_CBUTTON6_ACTION        1325
#define IDC_CBUTTON6_PATH          1326
#define IDC_CBUTTON6_BROWSE        1327

// Custom Button Icon controls
#define IDC_CBUTTON_ICON_LABEL     1330
#define IDC_CBUTTON1_ICON          1331
#define IDC_CBUTTON1_ICON_BROWSE   1332
#define IDC_CBUTTON1_ICON_CLEAR    1333
#define IDC_CBUTTON2_ICON          1334
#define IDC_CBUTTON2_ICON_BROWSE   1335
#define IDC_CBUTTON2_ICON_CLEAR    1336
#define IDC_CBUTTON3_ICON          1337
#define IDC_CBUTTON3_ICON_BROWSE   1338
#define IDC_CBUTTON3_ICON_CLEAR    1339
#define IDC_CBUTTON4_ICON          1340
#define IDC_CBUTTON4_ICON_BROWSE   1341
#define IDC_CBUTTON4_ICON_CLEAR    1342
#define IDC_CBUTTON5_ICON          1343
#define IDC_CBUTTON5_ICON_BROWSE   1344
#define IDC_CBUTTON5_ICON_CLEAR    1345
#define IDC_CBUTTON6_ICON          1346
#define IDC_CBUTTON6_ICON_BROWSE   1347
#define IDC_CBUTTON6_ICON_CLEAR    1348

// Icon row number labels
#define IDC_CBUTTON1_ICON_LABEL    1350
#define IDC_CBUTTON2_ICON_LABEL    1351
#define IDC_CBUTTON3_ICON_LABEL    1352
#define IDC_CBUTTON4_ICON_LABEL    1353
#define IDC_CBUTTON5_ICON_LABEL    1354
#define IDC_CBUTTON6_ICON_LABEL    1355

// Custom Button Tooltip/Label controls
#define IDC_CBUTTON_LABEL_LABEL    1360
#define IDC_CBUTTON1_LABEL         1361
#define IDC_CBUTTON2_LABEL         1362
#define IDC_CBUTTON3_LABEL         1363
#define IDC_CBUTTON4_LABEL         1364
#define IDC_CBUTTON5_LABEL         1365
#define IDC_CBUTTON6_LABEL         1366

// Mood tag configuration controls (General tab)
#define IDC_MOOD_TAG_LABEL         1146
#define IDC_MOOD_TAG_COMBO         1147

// Playback Preview section (General tab)
#define IDC_PLAYBACK_PREVIEW_GROUP      1148
#define IDC_SKIP_LOW_RATING_LABEL       1149
#define IDC_SKIP_LOW_RATING_COMBO       1150
#define IDC_SKIP_RATING_THRESHOLD_LABEL 1151
#define IDC_SKIP_RATING_THRESHOLD_COMBO 1152

// Spectrum Visualizer controls (General tab) - legacy, kept for reference
#define IDC_SPECTRUM_LABEL         1153
#define IDC_SPECTRUM_COMBO         1154

// Visualization section (General tab)
#define IDC_VIS_GROUP                1400
#define IDC_VIS_ENABLE_CHECK         1401
#define IDC_VIS_SPECTRUM_RADIO       1402
#define IDC_VIS_SPECTRUM_WIDTH_LABEL 1403
#define IDC_VIS_SPECTRUM_WIDTH_COMBO 1404
#define IDC_VIS_SPECTRUM_COLOR_LABEL 1405
#define IDC_VIS_SPECTRUM_COLOR_BTN   1406
#define IDC_VIS_SPECTRUM_SHAPE_LABEL 1407
#define IDC_VIS_SPECTRUM_SHAPE_COMBO 1408
#define IDC_VIS_WAVEFORM_RADIO       1409
#define IDC_VIS_WAVEFORM_COLOR_LABEL 1410
#define IDC_VIS_WAVEFORM_COLOR_BTN   1411
#define IDC_VIS_WAVEFORM_WIDTH_LABEL 1412
#define IDC_VIS_WAVEFORM_WIDTH_COMBO 1413
#define IDC_VIS_WAVEFORM_UNPLAYED_COLOR_LABEL 1414
#define IDC_VIS_WAVEFORM_UNPLAYED_COLOR_BTN   1415
#define IDC_VIS_60FPS_CHECK                   1420

// Online Artwork checkbox (Appearance tab)
#define IDC_ONLINE_ARTWORK_CHECK       1416
#define IDC_FOO_ARTWORK_LINK           1417
#define IDC_FOO_TRAYCONTROLS_LINK      1418
#define IDC_FOO_SVG_SERVICES_LINK      1419

// Color custom-enable checkboxes (Fonts & Colors tab)
#define IDC_COLORS_GROUP               1500
#define IDC_CUSTOM_BUTTON_ACCENT_CHECK 1501
#define IDC_CUSTOM_PLAY_ACCENT_CHECK   1502
#define IDC_CUSTOM_PROGRESS_ACCENT_CHECK 1503
#define IDC_CUSTOM_VOLUME_ACCENT_CHECK 1504
#define IDC_CUSTOM_HOVER_COLOR_CHECK   1505
#define IDC_CUSTOM_SPECTRUM_COLOR_CHECK 1506
#define IDC_CUSTOM_WAVEFORM_COLOR_CHECK 1507
#define IDC_CUSTOM_WAVEFORM_UNPLAYED_CHECK 1508

// New color picker buttons
#define IDC_PLAY_ACCENT_LABEL          1509
#define IDC_PLAY_ACCENT_BTN            1510
#define IDC_HOVER_COLOR_LABEL          1511
#define IDC_HOVER_COLOR_BTN            1512

// Profile configuration controls (Custom Button tab)
#define IDC_PROFILE_NAME_LABEL     1370
#define IDC_PROFILE_COMBO          1371
#define IDC_PROFILE_MENU_BTN       1372
